import type { ModelPolicy, ModelTaskType } from "./model-types.ts";

export const MODEL_POLICIES: Record<ModelTaskType, ModelPolicy> = {
  classification: {
    task_type: "classification",
    allowed_models: ["gpt-5.6-luna", "gemini-2.5-flash"],
    primary: "gpt-5.6-luna",
    fallback: ["gemini-2.5-flash"],
    max_attempts: 2,
    timeout_ms: 30_000,
    max_cost_per_run_usd: null,
    requires_cross_provider_fallback: true,
    requires_human_review: false,
  },
  fact_extraction: {
    task_type: "fact_extraction",
    allowed_models: ["gpt-5.6-luna", "gemini-2.5-flash"],
    primary: "gpt-5.6-luna",
    fallback: ["gemini-2.5-flash"],
    max_attempts: 2,
    timeout_ms: 45_000,
    max_cost_per_run_usd: null,
    requires_cross_provider_fallback: true,
    requires_human_review: false,
  },
  ai_fill: {
    task_type: "ai_fill",
    allowed_models: ["gemini-2.5-flash", "gpt-5.6-luna"],
    primary: "gemini-2.5-flash",
    fallback: ["gpt-5.6-luna"],
    max_attempts: 2,
    timeout_ms: 120_000,
    max_cost_per_run_usd: null,
    requires_cross_provider_fallback: true,
    requires_human_review: false,
  },
  legal_research: {
    task_type: "legal_research",
    allowed_models: ["gemini-2.5-pro", "gpt-5.6-terra"],
    primary: "gemini-2.5-pro",
    fallback: ["gpt-5.6-terra"],
    max_attempts: 2,
    timeout_ms: 180_000,
    max_cost_per_run_usd: null,
    requires_cross_provider_fallback: true,
    requires_human_review: false,
  },
  generation: {
    task_type: "generation",
    allowed_models: ["gemini-2.5-flash-lite", "gpt-5.6-terra"],
    primary: "gemini-2.5-flash-lite",
    fallback: ["gpt-5.6-terra"],
    max_attempts: 2,
    timeout_ms: 180_000,
    max_cost_per_run_usd: null,
    requires_cross_provider_fallback: true,
    requires_human_review: false,
  },
  review: {
    task_type: "review",
    allowed_models: ["gemini-2.5-flash", "gpt-5.6-terra"],
    primary: "gemini-2.5-flash",
    fallback: ["gpt-5.6-terra"],
    max_attempts: 2,
    timeout_ms: 180_000,
    max_cost_per_run_usd: null,
    requires_cross_provider_fallback: true,
    requires_human_review: false,
  },
  challenge: {
    task_type: "challenge",
    allowed_models: ["gemini-2.5-flash", "gpt-5.6-terra"],
    primary: "gemini-2.5-flash",
    fallback: ["gpt-5.6-terra"],
    max_attempts: 2,
    timeout_ms: 180_000,
    max_cost_per_run_usd: null,
    requires_cross_provider_fallback: true,
    requires_human_review: false,
  },
};

export function getModelPolicy(taskType: ModelTaskType): ModelPolicy {
  return MODEL_POLICIES[taskType];
}
