/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as VzyskanieZadolzhennostiRouteImport } from './routes/vzyskanie-zadolzhennosti'
import { Route as VyselenieArendatoraRouteImport } from './routes/vyselenie-arendatora'
import { Route as VozvratZalogaArendaRouteImport } from './routes/vozvrat-zaloga-arenda'
import { Route as SporSArendatoromRouteImport } from './routes/spor-s-arendatorom'
import { Route as SoprovozhdenieSdelkiRouteImport } from './routes/soprovozhdenie-sdelki'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RepresentationAbroadRouteImport } from './routes/representation-abroad'
import { Route as RepresentationRouteImport } from './routes/representation'
import { Route as RentalDisputesRouteImport } from './routes/rental-disputes'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ProverkaKvartiryMoskvaRouteImport } from './routes/proverka-kvartiry-moskva'
import { Route as NedvizhimostRouteImport } from './routes/nedvizhimost'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LitigationRouteImport } from './routes/litigation'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRentRouteImport } from './routes/commercial-rent'
import { Route as ArbitrazhnyeSporyRouteImport } from './routes/arbitrazhnye-spory'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceStatisticsRouteImport } from './routes/workspace.statistics'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace.settings'
import { Route as WorkspaceReviewsRouteImport } from './routes/workspace.reviews'
import { Route as WorkspaceLoginRouteImport } from './routes/workspace.login'
import { Route as WorkspaceLeadsRouteImport } from './routes/workspace.leads'
import { Route as WorkspaceDashboardRouteImport } from './routes/workspace.dashboard'
import { Route as WorkspaceCrmRouteImport } from './routes/workspace.crm'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as ApiWebhooksTelegramRouteImport } from './routes/api/webhooks/telegram'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const VzyskanieZadolzhennostiRoute = VzyskanieZadolzhennostiRouteImport.update({
  id: '/vzyskanie-zadolzhennosti',
  path: '/vzyskanie-zadolzhennosti',
  getParentRoute: () => rootRouteImport,
} as any)
const VyselenieArendatoraRoute = VyselenieArendatoraRouteImport.update({
  id: '/vyselenie-arendatora',
  path: '/vyselenie-arendatora',
  getParentRoute: () => rootRouteImport,
} as any)
const VozvratZalogaArendaRoute = VozvratZalogaArendaRouteImport.update({
  id: '/vozvrat-zaloga-arenda',
  path: '/vozvrat-zaloga-arenda',
  getParentRoute: () => rootRouteImport,
} as any)
const SporSArendatoromRoute = SporSArendatoromRouteImport.update({
  id: '/spor-s-arendatorom',
  path: '/spor-s-arendatorom',
  getParentRoute: () => rootRouteImport,
} as any)
const SoprovozhdenieSdelkiRoute = SoprovozhdenieSdelkiRouteImport.update({
  id: '/soprovozhdenie-sdelki',
  path: '/soprovozhdenie-sdelki',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentationAbroadRoute = RepresentationAbroadRouteImport.update({
  id: '/representation-abroad',
  path: '/representation-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentationRoute = RepresentationRouteImport.update({
  id: '/representation',
  path: '/representation',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalDisputesRoute = RentalDisputesRouteImport.update({
  id: '/rental-disputes',
  path: '/rental-disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProverkaKvartiryMoskvaRoute = ProverkaKvartiryMoskvaRouteImport.update({
  id: '/proverka-kvartiry-moskva',
  path: '/proverka-kvartiry-moskva',
  getParentRoute: () => rootRouteImport,
} as any)
const NedvizhimostRoute = NedvizhimostRouteImport.update({
  id: '/nedvizhimost',
  path: '/nedvizhimost',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LitigationRoute = LitigationRouteImport.update({
  id: '/litigation',
  path: '/litigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRentRoute = CommercialRentRouteImport.update({
  id: '/commercial-rent',
  path: '/commercial-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrazhnyeSporyRoute = ArbitrazhnyeSporyRouteImport.update({
  id: '/arbitrazhnye-spory',
  path: '/arbitrazhnye-spory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceStatisticsRoute = WorkspaceStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceReviewsRoute = WorkspaceReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceLoginRoute = WorkspaceLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceLeadsRoute = WorkspaceLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCrmRoute = WorkspaceCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => WorkspaceRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksTelegramRoute = ApiWebhooksTelegramRouteImport.update({
  id: '/api/webhooks/telegram',
  path: '/api/webhooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/arbitrazhnye-spory': typeof ArbitrazhnyeSporyRoute
  '/commercial-rent': typeof CommercialRentRoute
  '/contact': typeof ContactRoute
  '/contracts': typeof ContractsRoute
  '/litigation': typeof LitigationRoute
  '/login': typeof LoginRoute
  '/nedvizhimost': typeof NedvizhimostRoute
  '/proverka-kvartiry-moskva': typeof ProverkaKvartiryMoskvaRoute
  '/real-estate': typeof RealEstateRoute
  '/rental-disputes': typeof RentalDisputesRoute
  '/representation': typeof RepresentationRoute
  '/representation-abroad': typeof RepresentationAbroadRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soprovozhdenie-sdelki': typeof SoprovozhdenieSdelkiRoute
  '/spor-s-arendatorom': typeof SporSArendatoromRoute
  '/vozvrat-zaloga-arenda': typeof VozvratZalogaArendaRoute
  '/vyselenie-arendatora': typeof VyselenieArendatoraRoute
  '/vzyskanie-zadolzhennosti': typeof VzyskanieZadolzhennostiRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/api/chat': typeof ApiChatRoute
  '/workspace/crm': typeof WorkspaceCrmRoute
  '/workspace/dashboard': typeof WorkspaceDashboardRoute
  '/workspace/leads': typeof WorkspaceLeadsRoute
  '/workspace/login': typeof WorkspaceLoginRoute
  '/workspace/reviews': typeof WorkspaceReviewsRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/statistics': typeof WorkspaceStatisticsRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/arbitrazhnye-spory': typeof ArbitrazhnyeSporyRoute
  '/commercial-rent': typeof CommercialRentRoute
  '/contact': typeof ContactRoute
  '/contracts': typeof ContractsRoute
  '/litigation': typeof LitigationRoute
  '/login': typeof LoginRoute
  '/nedvizhimost': typeof NedvizhimostRoute
  '/proverka-kvartiry-moskva': typeof ProverkaKvartiryMoskvaRoute
  '/real-estate': typeof RealEstateRoute
  '/rental-disputes': typeof RentalDisputesRoute
  '/representation': typeof RepresentationRoute
  '/representation-abroad': typeof RepresentationAbroadRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soprovozhdenie-sdelki': typeof SoprovozhdenieSdelkiRoute
  '/spor-s-arendatorom': typeof SporSArendatoromRoute
  '/vozvrat-zaloga-arenda': typeof VozvratZalogaArendaRoute
  '/vyselenie-arendatora': typeof VyselenieArendatoraRoute
  '/vzyskanie-zadolzhennosti': typeof VzyskanieZadolzhennostiRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/api/chat': typeof ApiChatRoute
  '/workspace/crm': typeof WorkspaceCrmRoute
  '/workspace/dashboard': typeof WorkspaceDashboardRoute
  '/workspace/leads': typeof WorkspaceLeadsRoute
  '/workspace/login': typeof WorkspaceLoginRoute
  '/workspace/reviews': typeof WorkspaceReviewsRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/statistics': typeof WorkspaceStatisticsRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/arbitrazhnye-spory': typeof ArbitrazhnyeSporyRoute
  '/commercial-rent': typeof CommercialRentRoute
  '/contact': typeof ContactRoute
  '/contracts': typeof ContractsRoute
  '/litigation': typeof LitigationRoute
  '/login': typeof LoginRoute
  '/nedvizhimost': typeof NedvizhimostRoute
  '/proverka-kvartiry-moskva': typeof ProverkaKvartiryMoskvaRoute
  '/real-estate': typeof RealEstateRoute
  '/rental-disputes': typeof RentalDisputesRoute
  '/representation': typeof RepresentationRoute
  '/representation-abroad': typeof RepresentationAbroadRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soprovozhdenie-sdelki': typeof SoprovozhdenieSdelkiRoute
  '/spor-s-arendatorom': typeof SporSArendatoromRoute
  '/vozvrat-zaloga-arenda': typeof VozvratZalogaArendaRoute
  '/vyselenie-arendatora': typeof VyselenieArendatoraRoute
  '/vzyskanie-zadolzhennosti': typeof VzyskanieZadolzhennostiRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/api/chat': typeof ApiChatRoute
  '/workspace/crm': typeof WorkspaceCrmRoute
  '/workspace/dashboard': typeof WorkspaceDashboardRoute
  '/workspace/leads': typeof WorkspaceLeadsRoute
  '/workspace/login': typeof WorkspaceLoginRoute
  '/workspace/reviews': typeof WorkspaceReviewsRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/statistics': typeof WorkspaceStatisticsRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/arbitrazhnye-spory'
    | '/commercial-rent'
    | '/contact'
    | '/contracts'
    | '/litigation'
    | '/login'
    | '/nedvizhimost'
    | '/proverka-kvartiry-moskva'
    | '/real-estate'
    | '/rental-disputes'
    | '/representation'
    | '/representation-abroad'
    | '/reviews'
    | '/sitemap.xml'
    | '/soprovozhdenie-sdelki'
    | '/spor-s-arendatorom'
    | '/vozvrat-zaloga-arenda'
    | '/vyselenie-arendatora'
    | '/vzyskanie-zadolzhennosti'
    | '/workspace'
    | '/admin/reviews'
    | '/api/chat'
    | '/workspace/crm'
    | '/workspace/dashboard'
    | '/workspace/leads'
    | '/workspace/login'
    | '/workspace/reviews'
    | '/workspace/settings'
    | '/workspace/statistics'
    | '/api/webhooks/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/arbitrazhnye-spory'
    | '/commercial-rent'
    | '/contact'
    | '/contracts'
    | '/litigation'
    | '/login'
    | '/nedvizhimost'
    | '/proverka-kvartiry-moskva'
    | '/real-estate'
    | '/rental-disputes'
    | '/representation'
    | '/representation-abroad'
    | '/reviews'
    | '/sitemap.xml'
    | '/soprovozhdenie-sdelki'
    | '/spor-s-arendatorom'
    | '/vozvrat-zaloga-arenda'
    | '/vyselenie-arendatora'
    | '/vzyskanie-zadolzhennosti'
    | '/workspace'
    | '/admin/reviews'
    | '/api/chat'
    | '/workspace/crm'
    | '/workspace/dashboard'
    | '/workspace/leads'
    | '/workspace/login'
    | '/workspace/reviews'
    | '/workspace/settings'
    | '/workspace/statistics'
    | '/api/webhooks/telegram'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/arbitrazhnye-spory'
    | '/commercial-rent'
    | '/contact'
    | '/contracts'
    | '/litigation'
    | '/login'
    | '/nedvizhimost'
    | '/proverka-kvartiry-moskva'
    | '/real-estate'
    | '/rental-disputes'
    | '/representation'
    | '/representation-abroad'
    | '/reviews'
    | '/sitemap.xml'
    | '/soprovozhdenie-sdelki'
    | '/spor-s-arendatorom'
    | '/vozvrat-zaloga-arenda'
    | '/vyselenie-arendatora'
    | '/vzyskanie-zadolzhennosti'
    | '/workspace'
    | '/admin/reviews'
    | '/api/chat'
    | '/workspace/crm'
    | '/workspace/dashboard'
    | '/workspace/leads'
    | '/workspace/login'
    | '/workspace/reviews'
    | '/workspace/settings'
    | '/workspace/statistics'
    | '/api/webhooks/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArbitrazhnyeSporyRoute: typeof ArbitrazhnyeSporyRoute
  CommercialRentRoute: typeof CommercialRentRoute
  ContactRoute: typeof ContactRoute
  ContractsRoute: typeof ContractsRoute
  LitigationRoute: typeof LitigationRoute
  LoginRoute: typeof LoginRoute
  NedvizhimostRoute: typeof NedvizhimostRoute
  ProverkaKvartiryMoskvaRoute: typeof ProverkaKvartiryMoskvaRoute
  RealEstateRoute: typeof RealEstateRoute
  RentalDisputesRoute: typeof RentalDisputesRoute
  RepresentationRoute: typeof RepresentationRoute
  RepresentationAbroadRoute: typeof RepresentationAbroadRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoprovozhdenieSdelkiRoute: typeof SoprovozhdenieSdelkiRoute
  SporSArendatoromRoute: typeof SporSArendatoromRoute
  VozvratZalogaArendaRoute: typeof VozvratZalogaArendaRoute
  VyselenieArendatoraRoute: typeof VyselenieArendatoraRoute
  VzyskanieZadolzhennostiRoute: typeof VzyskanieZadolzhennostiRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiWebhooksTelegramRoute: typeof ApiWebhooksTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vzyskanie-zadolzhennosti': {
      id: '/vzyskanie-zadolzhennosti'
      path: '/vzyskanie-zadolzhennosti'
      fullPath: '/vzyskanie-zadolzhennosti'
      preLoaderRoute: typeof VzyskanieZadolzhennostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vyselenie-arendatora': {
      id: '/vyselenie-arendatora'
      path: '/vyselenie-arendatora'
      fullPath: '/vyselenie-arendatora'
      preLoaderRoute: typeof VyselenieArendatoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vozvrat-zaloga-arenda': {
      id: '/vozvrat-zaloga-arenda'
      path: '/vozvrat-zaloga-arenda'
      fullPath: '/vozvrat-zaloga-arenda'
      preLoaderRoute: typeof VozvratZalogaArendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spor-s-arendatorom': {
      id: '/spor-s-arendatorom'
      path: '/spor-s-arendatorom'
      fullPath: '/spor-s-arendatorom'
      preLoaderRoute: typeof SporSArendatoromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soprovozhdenie-sdelki': {
      id: '/soprovozhdenie-sdelki'
      path: '/soprovozhdenie-sdelki'
      fullPath: '/soprovozhdenie-sdelki'
      preLoaderRoute: typeof SoprovozhdenieSdelkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representation-abroad': {
      id: '/representation-abroad'
      path: '/representation-abroad'
      fullPath: '/representation-abroad'
      preLoaderRoute: typeof RepresentationAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representation': {
      id: '/representation'
      path: '/representation'
      fullPath: '/representation'
      preLoaderRoute: typeof RepresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-disputes': {
      id: '/rental-disputes'
      path: '/rental-disputes'
      fullPath: '/rental-disputes'
      preLoaderRoute: typeof RentalDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proverka-kvartiry-moskva': {
      id: '/proverka-kvartiry-moskva'
      path: '/proverka-kvartiry-moskva'
      fullPath: '/proverka-kvartiry-moskva'
      preLoaderRoute: typeof ProverkaKvartiryMoskvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nedvizhimost': {
      id: '/nedvizhimost'
      path: '/nedvizhimost'
      fullPath: '/nedvizhimost'
      preLoaderRoute: typeof NedvizhimostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/litigation': {
      id: '/litigation'
      path: '/litigation'
      fullPath: '/litigation'
      preLoaderRoute: typeof LitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-rent': {
      id: '/commercial-rent'
      path: '/commercial-rent'
      fullPath: '/commercial-rent'
      preLoaderRoute: typeof CommercialRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrazhnye-spory': {
      id: '/arbitrazhnye-spory'
      path: '/arbitrazhnye-spory'
      fullPath: '/arbitrazhnye-spory'
      preLoaderRoute: typeof ArbitrazhnyeSporyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/statistics': {
      id: '/workspace/statistics'
      path: '/statistics'
      fullPath: '/workspace/statistics'
      preLoaderRoute: typeof WorkspaceStatisticsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/reviews': {
      id: '/workspace/reviews'
      path: '/reviews'
      fullPath: '/workspace/reviews'
      preLoaderRoute: typeof WorkspaceReviewsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/login': {
      id: '/workspace/login'
      path: '/login'
      fullPath: '/workspace/login'
      preLoaderRoute: typeof WorkspaceLoginRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/leads': {
      id: '/workspace/leads'
      path: '/leads'
      fullPath: '/workspace/leads'
      preLoaderRoute: typeof WorkspaceLeadsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/dashboard': {
      id: '/workspace/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/crm': {
      id: '/workspace/crm'
      path: '/crm'
      fullPath: '/workspace/crm'
      preLoaderRoute: typeof WorkspaceCrmRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/telegram': {
      id: '/api/webhooks/telegram'
      path: '/api/webhooks/telegram'
      fullPath: '/api/webhooks/telegram'
      preLoaderRoute: typeof ApiWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminReviewsRoute: typeof AdminReviewsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReviewsRoute: AdminReviewsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceCrmRoute: typeof WorkspaceCrmRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceLeadsRoute: typeof WorkspaceLeadsRoute
  WorkspaceLoginRoute: typeof WorkspaceLoginRoute
  WorkspaceReviewsRoute: typeof WorkspaceReviewsRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceStatisticsRoute: typeof WorkspaceStatisticsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceCrmRoute: WorkspaceCrmRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceLeadsRoute: WorkspaceLeadsRoute,
  WorkspaceLoginRoute: WorkspaceLoginRoute,
  WorkspaceReviewsRoute: WorkspaceReviewsRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceStatisticsRoute: WorkspaceStatisticsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  ArbitrazhnyeSporyRoute: ArbitrazhnyeSporyRoute,
  CommercialRentRoute: CommercialRentRoute,
  ContactRoute: ContactRoute,
  ContractsRoute: ContractsRoute,
  LitigationRoute: LitigationRoute,
  LoginRoute: LoginRoute,
  NedvizhimostRoute: NedvizhimostRoute,
  ProverkaKvartiryMoskvaRoute: ProverkaKvartiryMoskvaRoute,
  RealEstateRoute: RealEstateRoute,
  RentalDisputesRoute: RentalDisputesRoute,
  RepresentationRoute: RepresentationRoute,
  RepresentationAbroadRoute: RepresentationAbroadRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoprovozhdenieSdelkiRoute: SoprovozhdenieSdelkiRoute,
  SporSArendatoromRoute: SporSArendatoromRoute,
  VozvratZalogaArendaRoute: VozvratZalogaArendaRoute,
  VyselenieArendatoraRoute: VyselenieArendatoraRoute,
  VzyskanieZadolzhennostiRoute: VzyskanieZadolzhennostiRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiWebhooksTelegramRoute: ApiWebhooksTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
